name: Publish Extension
on:
  workflow_dispatch:

jobs:
  publish_extension:
    name: Publish Extension
    runs-on: [ubuntu-latest] 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.MARKETPLACEAUTH }}