name: Publish Extension

on: workflow_dispatch

jobs:
  publish_extension:
    name: Publish Extension
    runs-on: [ubuntu-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install

      - name: Get package info
        id: package
        uses: kylejrp/action-nodejs-package-info@v1.2
      - run: echo ${{ steps.package.outputs.version }}

      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   id: publishToOpenVSX
      #   with:
      #     pat: ${{ secrets.VSXAUTH }}

      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.MARKETPLACEAUTH}}
      #     registryUrl: https://marketplace.visualstudio.com
      #     extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}

      # - name: Publish Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     name: Extension Release ${{ steps.package.outputs.version }}
      #     tag_name: ${{ steps.package.outputs.version }}
      #     body_path: .github/release.txt
      #     files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}