name: Publish Extension
on:
  workflow_dispatch:

jobs:
  publish_extension:
    name: Publish Extension
    runs-on: [ubuntu-latest] 
    steps:
      - name: Test
        run: ls
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.MARKETPLACEAUTH }}